export const COUNTRY_LIST = [
  'Spain',
  'Italy',
  'Hungary',
  'India',
  'Belgium',
  'Czech Republic',
  'Chile',
  'Sweden',
  'Norway',
  'France',
  'USA',
  'United Kingdom',
  'Netherlands',
  'Brazil',
  'Austria',
  'Australia',
  'Poland',
  'Ireland',
  'Germany',
  'Denmark',
  'Canada',
  'Finland',
  'Portugal',
] as const;

export const GENRE_LIST = [
  'All',
  'Soundtrack',
  'Electronica/Dance',
  'Easy Listening',
  'Reggae',
  'Blues',
  'R&B/Soul',
  'Alternative',
  'TV Shows',
  'Bossa Nova',
  'Science Fiction',
  'Latin',
  'Hip Hop/Rap',
  'Rock And Roll',
  'Drama',
  'Opera',
  'Sci Fi & Fantasy',
  'Comedy',
  'Classical',
  'Pop',
  'Alternative & Punk Rock',
  'Rock',
  'Metal',
  'Jazz',
  'World',
  'Heavy Metal',
] as const;
