export const COUNTRY_LIST = [
    "Argentina",
    "Spain",
    "Italy",
    "Hungary",
    "India",
    "Belgium",
    "Czech Republic",
    "Chile",
    "Sweden",
    "Norway",
    "France",
    "USA",
    "United Kingdom",
    "Netherlands",
    "Brazil",
    "Austria",
    "Australia",
    "Poland",
    "Ireland",
    "Germany",
    "Denmark",
    "Canada",
    "Finland",
    "Portugal"
];

export const GENRE_LIST = [
    "Soundtrack",
    "Electronica/Dance",
    "Easy Listening",
    "Reggae",
    "Blues",
    "R&B/Soul",
    "Alternative",
    "TV Shows",
    "Bossa Nova",
    "Science Fiction",
    "Latin",
    "Hip Hop/Rap",
    "Rock And Roll",
    "Drama",
    "Opera",
    "Sci Fi & Fantasy",
    "Comedy",
    "Classical",
    "Pop",
    "Alternative & Punk Rock",
    "Metal",
    "Jazz",
    "World",
    "Heavy Metal"
];